import type { WordlePuzzle } from './types'

/** Hardcoded puzzle for the first playable milestone. */
export const mockPuzzle: WordlePuzzle = {
  word: 'appel',
  wordLength: 5,
  maxAttempts: 6,
  allowedWords: [
    'aarde',
    'appel',
    'bloem',
    'boter',
    'brood',
    'delta',
    'droom',
    'fiets',
    'graan',
    'groen',
    'haven',
    'ijzer',
    'kaars',
    'licht',
    'motor',
    'nacht',
    'noord',
    'paard',
    'plant',
    'radio',
    'regen',
    'slang',
    'stoel',
    'tafel',
    'toren',
    'trein',
    'vloer',
    'vogel',
    'water',
    'zomer',
  ],
}
